spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.web.cors.allowed-origins=${FRONTEND_URL}
payu.key=${PAYU_KEY}
payu.salt=${PAYU_SALT}
payu.url=https://test.payu.in/_payment
groq.api.key=${GROQ_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
fast2sms.api.key=${FAST2SMS_KEY}
fast2sms.enabled=true
otp.expiry.minutes=10
datagov.api.key=${DATAGOV_KEY}
twilio.account-sid=${TWILIO_SID}
twilio.auth-token=${TWILIO_TOKEN}
twilio.phone-number=+15076985286
twilio.enabled=false